apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightly
  labels:
    app: lightly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lightly
  template:
    metadata:
      labels:
        app: lightly
    spec:
      containers:
      - name: lightly
        image: localhost:32000/lightly
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lightly-service
spec:
  selector:
    app: lightly
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lightly-ingress
spec:
  rules:
  - host: lightly.forno96.it
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lightly-service
            port:
              number: 80
